import { Kysely, PostgresDialect } from 'kysely'
import pg from 'pg'
import type { DB } from './types.js' // generated by codegen (Task 5); use `any` until then

let pool: pg.Pool | undefined
let db: Kysely<DB> | undefined

export function getPool(): pg.Pool {
  if (!pool) {
    const connectionString = process.env.DATABASE_URL
    if (!connectionString) throw new Error('DATABASE_URL is not set')
    pool = new pg.Pool({ connectionString, max: 10 })
  }
  return pool
}

export function getDb(): Kysely<DB> {
  if (!db) db = new Kysely<DB>({ dialect: new PostgresDialect({ pool: getPool() }) })
  return db
}

export async function closeDb(): Promise<void> {
  await db?.destroy()
  db = undefined
  pool = undefined
}
