/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUsers {
  auth_user_id: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface BdMigrationMeta {
  created_at: Generated<Timestamp>;
  key: string;
  value: string | null;
}

export interface BeanPhotos {
  app_user_id: string | null;
  attribution: string | null;
  bean_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  sort_order: Generated<number>;
  source: string | null;
  updated_at: Generated<Timestamp>;
  url: string;
}

export interface BeanPurchaseLinks {
  active: Generated<boolean>;
  bean_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_affiliate: Generated<boolean>;
  link_category: Generated<string>;
  price_krw: number | null;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
  url: string;
  vendor: string;
}

export interface Beans {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  notes: string | null;
  origin: string | null;
  process: string | null;
  roast_level: string | null;
  roaster: string | null;
  updated_at: Generated<Timestamp>;
}

export interface BeanSummaries {
  has_ai: boolean | null;
  id: string | null;
  latest_recipe_at: Timestamp | null;
  name: string | null;
  notes: string | null;
  origin: string | null;
  process: string | null;
  recipe_count: Int8 | null;
  roast_level: string | null;
  roaster: string | null;
}

export interface Drippers {
  class: string;
  continuum_position: Numeric | null;
  created_at: Generated<Timestamp>;
  filter_type: string | null;
  geometry: string | null;
  hole_spec: Generated<Json>;
  id: Generated<string>;
  name: string;
  notes: string | null;
  recommended_dose_range: Generated<Json>;
  size_models: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Feedback {
  actual: Json | null;
  bean_id: string | null;
  comment: string | null;
  created_at: Generated<Timestamp>;
  desired_direction: string[] | null;
  id: Generated<string>;
  next_hint: string[] | null;
  owner_id: string | null;
  quick_tags: string[] | null;
  ratings: Json | null;
  raw_comment: string | null;
  recipe_code: string;
  source: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface GrinderCalibration {
  anchor_method: string | null;
  app_user_id: string;
  created_at: Generated<Timestamp>;
  from_grinder_id: string | null;
  from_label: string;
  id: Generated<string>;
  notes: string | null;
  samples: Generated<Json>;
  source: Generated<string>;
  to_grinder_id: string | null;
  to_label: string;
  updated_at: Generated<Timestamp>;
}

export interface Grinders {
  anchor_point: Json | null;
  brew_method_ranges: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  notes: string | null;
  stepless: Generated<boolean>;
  um_per_click_est: Numeric | null;
  um_per_click_source: string | null;
  updated_at: Generated<Timestamp>;
  zero_ref: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface Preferences {
  created_at: Generated<Timestamp>;
  default_params: Generated<Json>;
  dislikes: Generated<string[]>;
  id: Generated<string>;
  likes: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface Recipes {
  adjustment_from_previous: string | null;
  bean_id: string | null;
  bean_snapshot: Json | null;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  dripper_portability: Json | null;
  id: Generated<string>;
  intent: string[] | null;
  is_official: Generated<boolean>;
  method: string;
  notes: string | null;
  owner_id: string | null;
  params: Generated<Json>;
  parent_code: string | null;
  status: Generated<string>;
  steps: Generated<Json>;
  superseded_by: string | null;
  supersedes: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface SavedBeans {
  app_user_id: string;
  bean_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
}

export interface SavedRecipes {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  recipe_code: string;
  snapshot: Json | null;
}

export interface UserGear {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  dripper_id: string | null;
  grinder_id: string | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  kind: string;
  label: string;
  updated_at: Generated<Timestamp>;
}

export interface UserIdentities {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  external_key: string;
  id: Generated<string>;
  provider: string;
  updated_at: Generated<Timestamp>;
  verified: Generated<boolean>;
}

export interface DB {
  app_users: AppUsers;
  bd_migration_meta: BdMigrationMeta;
  bean_photos: BeanPhotos;
  bean_purchase_links: BeanPurchaseLinks;
  bean_summaries: BeanSummaries;
  beans: Beans;
  drippers: Drippers;
  feedback: Feedback;
  grinder_calibration: GrinderCalibration;
  grinders: Grinders;
  pgmigrations: Pgmigrations;
  preferences: Preferences;
  recipes: Recipes;
  saved_beans: SavedBeans;
  saved_recipes: SavedRecipes;
  user_gear: UserGear;
  user_identities: UserIdentities;
}
